### ISSUE TITLE
why not use norm(p=1) replace twice norm()?

### ISSUE THREAD

**Issue by LitterMa-820** [Adonis-galaxy/DepthCLIP#1]
In the code of zeroshot_classifier, I can't understand these codes:

class_embeddings = model.encode_text(texts)
class_embeddings /= class_embeddings.norm(dim=-1, keepdim=True)
class_embedding = class_embeddings.mean(dim=0)
class_embedding /= class_embedding.norm()

why not use norm(p=1) replace twice norm()?
like class_embeddings /= class_embeddings.norm(dim=-1, keepdim=True,p=1)

**Comment by Adonis-galaxy** [comment]
Hi, Thanks for your advice and your interest in our code. Please feel free to contact us any time if you have any problems or advice~
