### ISSUE TITLE
在读完了您团队的论文和在monoclip中的部分代码后，我想请教以下问题

### ISSUE THREAD

**Issue by LitterMa-820** [Adonis-galaxy/DepthCLIP#2]
1、您给出的代码中Clip的源代码是经过修改的吗？我发现和原始的CLIP输出的形状不一致，输出的结果固定有221个批次屎代表把一张图片分为221个区域吗？
2、monoclip文件中的zeroshot_classifier代码
                class_embeddings = model.encode_text(texts)  # embed with text encoder
                class_embeddings /= class_embeddings.norm(dim=-1, keepdim=True)
                * class_embedding = class_embeddings.mean(dim=0)
                * class_embedding /= class_embedding.norm()
似乎将text_encode给出的结果进行了两次范数相除，虽然第二次范数计算一定为1符合论文中给出的相似度公式，但为什么要多做这么一步呢？
若您能提供解答，我感激不尽

**Comment by Adonis-galaxy** [comment]
Hi,
Thanks for your interest in our work.
For Q1. We remove the final layer of CLIP and use the layer before the final layer as the feature map, which would be 13*17*C, and 13*17=221.

For Q2. The operation in the code is the mathematical equivalent to equations we wrote in the paper, and I believe from an implementation perspective, there are multiple ways to conduct this. My implementation might not be the perfect one, and you could try to modify this step if you want.
